import { Trash2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { RECOMMENDATION_CATEGORY_LABELS } from "@/types";
import type { Recommendation } from "@/types";

interface Props {
  data: { items: Recommendation[] };
  onChange?: (data: { items: Recommendation[] }) => void;
}

const CATEGORY_ORDER = Object.keys(RECOMMENDATION_CATEGORY_LABELS);

const RecommendationsSection = ({ data, onChange }: Props) => {
  const items = data?.items ?? [];

  const remove = (idx: number) => {
    onChange?.({ ...data, items: items.filter((_, i) => i !== idx) });
  };

  // Group items by category, preserving CATEGORY_ORDER
  const grouped = new Map<string, { item: Recommendation; idx: number }[]>();
  items.forEach((item, idx) => {
    const key = item.category || "other";
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key)!.push({ item, idx });
  });

  // Sort groups: known categories in order first, then unknown categories
  const sortedKeys = [...grouped.keys()].sort((a, b) => {
    const ai = CATEGORY_ORDER.indexOf(a);
    const bi = CATEGORY_ORDER.indexOf(b);
    if (ai === -1 && bi === -1) return a.localeCompare(b);
    if (ai === -1) return 1;
    if (bi === -1) return -1;
    return ai - bi;
  });

  return (
    <div className="space-y-6">
      <div>
        <h2 className="text-lg font-semibold text-foreground mb-1">Recommendations</h2>
        <p className="text-xs text-muted-foreground">
          Tailored best practices generated by research
        </p>
      </div>

      {items.length === 0 ? (
        <div className="rounded-lg border border-dashed border-border bg-surface-1 px-6 py-10 text-center">
          <p className="text-sm text-muted-foreground">
            No recommendations yet. Run <code className="text-xs bg-surface-2 px-1.5 py-0.5 rounded">/mcs-research</code> to generate.
          </p>
        </div>
      ) : (
        <div className="space-y-5">
          {sortedKeys.map((cat) => {
            const entries = grouped.get(cat)!;
            const label = RECOMMENDATION_CATEGORY_LABELS[cat] ?? cat;
            return (
              <div key={cat}>
                <h3 className="text-sm font-medium text-foreground mb-2">{label}</h3>
                <div className="space-y-1.5">
                  {entries.map(({ item, idx }) => (
                    <div
                      key={idx}
                      className={`group flex items-start gap-2 rounded-md px-3 py-2 text-sm ${
                        item.source === "tailored"
                          ? "border-l-2 border-primary/60 bg-primary/5"
                          : "bg-surface-1"
                      }`}
                    >
                      <span className="mt-1 shrink-0 text-muted-foreground">&#8226;</span>
                      <span className="flex-1 text-foreground/90">{item.text}</span>
                      {item.source === "tailored" && (
                        <span className="shrink-0 mt-0.5 rounded bg-primary/10 px-1.5 py-0.5 text-[10px] font-medium text-primary">
                          Tailored
                        </span>
                      )}
                      {onChange && (
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-6 w-6 shrink-0 opacity-0 group-hover:opacity-100 transition-opacity text-destructive"
                          onClick={() => remove(idx)}
                        >
                          <Trash2 className="h-3 w-3" />
                        </Button>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};

export default RecommendationsSection;
