// Auto-generated system color icon registry (from Figma)
// Source: Figma file '*Deprecated* System color icons'

export interface SystemColorIcon {
  key: string;
  label: string;
}

export const SYSTEM_COLOR_ICONS: SystemColorIcon[] = [
  { key: 'add-circle', label: 'Add Circle' },
  { key: 'add-starburst', label: 'Add Starburst' },
  { key: 'airplane', label: 'Airplane' },
  { key: 'alert', label: 'Alert' },
  { key: 'alert-badge', label: 'Alert Badge' },
  { key: 'alert-urgent', label: 'Alert Urgent' },
  { key: 'animal-paw-print', label: 'Animal Paw Print' },
  { key: 'approvals-app', label: 'Approvals App' },
  { key: 'apps', label: 'Apps' },
  { key: 'apps-list', label: 'Apps List' },
  { key: 'apps-list-detail', label: 'Apps List Detail' },
  { key: 'arrow-clockwise-dashes', label: 'Arrow Clockwise Dashes' },
  { key: 'arrow-clockwise-dashes-settings', label: 'Arrow Clockwise Dashes Settings' },
  { key: 'arrow-square', label: 'Arrow Square' },
  { key: 'arrow-sync', label: 'Arrow Sync' },
  { key: 'arrow-trending-lines', label: 'Arrow Trending Lines' },
  { key: 'beach', label: 'Beach' },
  { key: 'bell', label: 'Bell' },
  { key: 'board', label: 'Board' },
  { key: 'book', label: 'Book' },
  { key: 'book-contacts', label: 'Book Contacts' },
  { key: 'book-database', label: 'Book Database' },
  { key: 'book-open', label: 'Book Open' },
  { key: 'book-open-lightbulb', label: 'Book Open Lightbulb' },
  { key: 'book-star', label: 'Book Star' },
  { key: 'bookmark', label: 'Bookmark' },
  { key: 'bot', label: 'Bot' },
  { key: 'brain', label: 'Brain' },
  { key: 'bot-sparkle', label: 'Bot Sparkle' },
  { key: 'briefcase', label: 'Briefcase' },
  { key: 'building', label: 'Building' },
  { key: 'building-government', label: 'Building Government' },
  { key: 'building-government-search', label: 'Building Government Search' },
  { key: 'building-home', label: 'Building Home' },
  { key: 'building-multiple', label: 'Building Multiple' },
  { key: 'building-people', label: 'Building People' },
  { key: 'building-store', label: 'Building Store' },
  { key: 'calendar', label: 'Calendar' },
  { key: 'calendar-cancel', label: 'Calendar Cancel' },
  { key: 'calendar-checkmark', label: 'Calendar Checkmark' },
  { key: 'calendar-clock', label: 'Calendar Clock' },
  { key: 'calendar-data-bar', label: 'Calendar Data Bar' },
  { key: 'calendar-edit', label: 'Calendar Edit' },
  { key: 'calendar-people', label: 'Calendar People' },
  { key: 'calendar-sync', label: 'Calendar Sync' },
  { key: 'calculator', label: 'Calculator' },
  { key: 'camera', label: 'Camera' },
  { key: 'certificate', label: 'Certificate' },
  { key: 'chart-multiple', label: 'Chart Multiple' },
  { key: 'chat', label: 'Chat' },
  { key: 'chat-add', label: 'Chat Add' },
  { key: 'chat-bubbles-question', label: 'Chat Bubbles Question' },
  { key: 'chat-multiple', label: 'Chat Multiple' },
  { key: 'checkbox', label: 'Checkbox' },
  { key: 'checkbox-person', label: 'Checkbox Person' },
  { key: 'checkmark-circle', label: 'Checkmark Circle' },
  { key: 'clipboard', label: 'Clipboard' },
  { key: 'clipboard-task', label: 'Clipboard Task' },
  { key: 'clipboard-text-edit', label: 'Clipboard Text Edit' },
  { key: 'clock', label: 'Clock' },
  { key: 'clock-alarm', label: 'Clock Alarm' },
  { key: 'cloud', label: 'Cloud' },
  { key: 'cloud-dismiss', label: 'Cloud Dismiss' },
  { key: 'cloud-words', label: 'Cloud Words' },
  { key: 'code', label: 'Code' },
  { key: 'code-block', label: 'Code Block' },
  { key: 'coin-multiple', label: 'Coin Multiple' },
  { key: 'comment', label: 'Comment' },
  { key: 'comment-multiple', label: 'Comment Multiple' },
  { key: 'compass', label: 'Compass' },
  { key: 'contact-card', label: 'Contact Card' },
  { key: 'content-view', label: 'Content View' },
  { key: 'crown', label: 'Crown' },
  { key: 'data-area', label: 'Data Area' },
  { key: 'data-bar-vertical-ascending', label: 'Data Bar Vertical Ascending' },
  { key: 'data-line', label: 'Data Line' },
  { key: 'data-pie', label: 'Data Pie' },
  { key: 'data-scatter', label: 'Data Scatter' },
  { key: 'data-trending', label: 'Data Trending' },
  { key: 'database', label: 'Database' },
  { key: 'design-ideas', label: 'Design Ideas' },
  { key: 'diamond', label: 'Diamond' },
  { key: 'dismiss-circle', label: 'Dismiss Circle' },
  { key: 'diversity', label: 'Diversity' },
  { key: 'document', label: 'Document' },
  { key: 'document-add', label: 'Document Add' },
  { key: 'document-edit', label: 'Document Edit' },
  { key: 'document-folder', label: 'Document Folder' },
  { key: 'document-lock', label: 'Document Lock' },
  { key: 'document-text', label: 'Document Text' },
  { key: 'drafts', label: 'Drafts' },
  { key: 'edit', label: 'Edit' },
  { key: 'error-circle', label: 'Error Circle' },
  { key: 'fast-forward-circle', label: 'Fast Forward Circle' },
  { key: 'fingerprint', label: 'Fingerprint' },
  { key: 'flag', label: 'Flag' },
  { key: 'food', label: 'Food' },
  { key: 'form', label: 'Form' },
  { key: 'funnel', label: 'Funnel' },
  { key: 'game-chat', label: 'Game Chat' },
  { key: 'gauge', label: 'Gauge' },
  { key: 'gavel', label: 'Gavel' },
  { key: 'gift', label: 'Gift' },
  { key: 'gift-card', label: 'Gift Card' },
  { key: 'globe', label: 'Globe' },
  { key: 'globe-shield', label: 'Globe Shield' },
  { key: 'graduation-cap', label: 'Graduation Cap' },
  { key: 'guest', label: 'Guest' },
  { key: 'handshake', label: 'Handshake' },
  { key: 'hashtag', label: 'Hashtag' },
  { key: 'headphones', label: 'Headphones' },
  { key: 'headset', label: 'Headset' },
  { key: 'heart', label: 'Heart' },
  { key: 'history', label: 'History' },
  { key: 'home', label: 'Home' },
  { key: 'hourglass', label: 'Hourglass' },
  { key: 'image', label: 'Image' },
  { key: 'image-off', label: 'Image Off' },
  { key: 'laptop', label: 'Laptop' },
  { key: 'layer-diagonal-person', label: 'Layer Diagonal Person' },
  { key: 'leaf', label: 'Leaf' },
  { key: 'library', label: 'Library' },
  { key: 'lightbulb', label: 'Lightbulb' },
  { key: 'lightbulb-checkmark', label: 'Lightbulb Checkmark' },
  { key: 'lightbulb-filament', label: 'Lightbulb Filament' },
  { key: 'lightning-bolt', label: 'Lightning Bolt' },
  { key: 'link', label: 'Link' },
  { key: 'link-multiple', label: 'Link Multiple' },
  { key: 'list-bar', label: 'List Bar' },
  { key: 'location-ripple', label: 'Location Ripple' },
  { key: 'lock-closed', label: 'Lock Closed' },
  { key: 'lock-shield', label: 'Lock Shield' },
  { key: 'mail', label: 'Mail' },
  { key: 'mail-alert', label: 'Mail Alert' },
  { key: 'mail-clock', label: 'Mail Clock' },
  { key: 'mail-multiple', label: 'Mail Multiple' },
  { key: 'megaphone-loud', label: 'Megaphone Loud' },
  { key: 'mic', label: 'Mic' },
  { key: 'molecule', label: 'Molecule' },
  { key: 'news', label: 'News' },
  { key: 'notebook', label: 'Notebook' },
  { key: 'notebook-question-mark', label: 'Notebook Question Mark' },
  { key: 'number-symbol-square', label: 'Number Symbol Square' },
  { key: 'options', label: 'Options' },
  { key: 'org', label: 'Org' },
  { key: 'package', label: 'Package' },
  { key: 'paint-brush', label: 'Paint Brush' },
  { key: 'patient', label: 'Patient' },
  { key: 'paw', label: 'Paw' },
  { key: 'people', label: 'People' },
  { key: 'people-add', label: 'People Add' },
  { key: 'people-chat', label: 'People Chat' },
  { key: 'people-home', label: 'People Home' },
  { key: 'people-interwoven', label: 'People Interwoven' },
  { key: 'people-list', label: 'People List' },
  { key: 'people-sync', label: 'People Sync' },
  { key: 'people-team', label: 'People Team' },
  { key: 'person', label: 'Person' },
  { key: 'person-add', label: 'Person Add' },
  { key: 'person-available', label: 'Person Available' },
  { key: 'person-edit', label: 'Person Edit' },
  { key: 'person-feedback', label: 'Person Feedback' },
  { key: 'person-heart', label: 'Person Heart' },
  { key: 'person-key', label: 'Person Key' },
  { key: 'person-starburst', label: 'Person Starburst' },
  { key: 'person-tentative', label: 'Person Tentative' },
  { key: 'person-warning', label: 'Person Warning' },
  { key: 'phone', label: 'Phone' },
  { key: 'phone-laptop', label: 'Phone Laptop' },
  { key: 'pin', label: 'Pin' },
  { key: 'planet', label: 'Planet' },
  { key: 'poll', label: 'Poll' },
  { key: 'premium', label: 'Premium' },
  { key: 'puzzle-piece', label: 'Puzzle Piece' },
  { key: 'question-circle', label: 'Question Circle' },
  { key: 'receipt', label: 'Receipt' },
  { key: 'reward', label: 'Reward' },
  { key: 'ribbon', label: 'Ribbon' },
  { key: 'rocket', label: 'Rocket' },
  { key: 'ribbon-star', label: 'Ribbon Star' },
  { key: 'savings', label: 'Savings' },
  { key: 'scales', label: 'Scales' },
  { key: 'scan-person', label: 'Scan Person' },
  { key: 'scan-type', label: 'Scan Type' },
  { key: 'search-sparkle', label: 'Search Sparkle' },
  { key: 'search-visual', label: 'Search Visual' },
  { key: 'send', label: 'Send' },
  { key: 'send-clock', label: 'Send Clock' },
  { key: 'settings', label: 'Settings' },
  { key: 'share-android', label: 'Share Android' },
  { key: 'share-ios', label: 'Share iOS' },
  { key: 'shield', label: 'Shield' },
  { key: 'shield-checkmark', label: 'Shield Checkmark' },
  { key: 'shifts', label: 'Shifts' },
  { key: 'signature', label: 'Signature' },
  { key: 'shopping-cart', label: 'Shopping Cart' },
  { key: 'slide-text-sparkle', label: 'Slide Text Sparkle' },
  { key: 'sparkle', label: 'Sparkle' },
  { key: 'sport', label: 'Sport' },
  { key: 'star', label: 'Star' },
  { key: 'star-settings', label: 'Star Settings' },
  { key: 'stethoscope', label: 'Stethoscope' },
  { key: 'table', label: 'Table' },
  { key: 'target', label: 'Target' },
  { key: 'tent', label: 'Tent' },
  { key: 'text-bullet-list-square', label: 'Text Bullet List Square' },
  { key: 'text-bullet-list-square-sparkle', label: 'Text Bullet List Square Sparkle' },
  { key: 'text-edit-style', label: 'Text Edit Style' },
  { key: 'toolbox', label: 'Toolbox' },
  { key: 'trophy', label: 'Trophy' },
  { key: 'truck', label: 'Truck' },
  { key: 'vault', label: 'Vault' },
  { key: 'video', label: 'Video' },
  { key: 'wand', label: 'Wand' },
  { key: 'warning', label: 'Warning' },
  { key: 'weather-snowflake', label: 'Weather Snowflake' },
  { key: 'weather-sunny-low', label: 'Weather Sunny Low' },
  { key: 'wifi', label: 'WiFi' },
  { key: 'wifi-warning', label: 'WiFi Warning' },
  { key: 'wrench', label: 'Wrench' },
  { key: 'wrench-screwdriver', label: 'Wrench Screwdriver' },
  { key: 'home-empty', label: 'Home Empty' },
  { key: 'chat-history', label: 'Chat History' },
  { key: 'circle-multiple-hint-checkmark', label: 'Circle Multiple Hint Checkmark' },
  { key: 'chat-empty', label: 'Chat Empty' },
  { key: 'search', label: 'Search' },
  { key: 'agents', label: 'Agents' },
  { key: 'agents-add', label: 'Agents Add' },
  { key: 'ai-teammate', label: 'AI Teammate' },
];

/** Get the import path for a system color icon SVG */
export function getSystemColorIconPath(key: string): string {
  return `/icons/system-color/${key}.svg`;
}

/** Parse an iconKey that may contain a "syscolor:" prefix from the icon picker.
 *  Returns { systemColorIcon, iconKey } — one will be set, the other undefined. */
export function parseSysColorKey(iconKey: string): { systemColorIcon?: string; iconKey?: string } {
  if (iconKey.startsWith('syscolor:')) {
    return { systemColorIcon: iconKey.slice(9), iconKey: undefined };
  }
  return { systemColorIcon: undefined, iconKey };
}

/** Curated icon catalog with visual descriptions for LLM-based selection */
export const ICON_CATALOG = [
  { key: 'receipt', visual: 'a paper receipt/bill', use: 'finance, invoices, payments, accounting' },
  { key: 'coin-multiple', visual: 'stacked gold coins', use: 'sales, revenue, money, deals' },
  { key: 'calculator', visual: 'a calculator with buttons', use: 'accounting, math, budgets, expenses' },
  { key: 'savings', visual: 'a piggy bank', use: 'savings, cost reduction, frugality' },
  { key: 'headset', visual: 'a customer support headset', use: 'customer support, IT help desk, call center' },
  { key: 'people-team', visual: 'group of three people', use: 'HR, team management, recruiting, hiring' },
  { key: 'people-add', visual: 'person with a plus sign', use: 'onboarding, new hires, adding team members' },
  { key: 'person-edit', visual: 'person with a pencil', use: 'employee profiles, HR records, personnel' },
  { key: 'clipboard-task', visual: 'clipboard with a checkmark', use: 'project management, tasks, to-dos, tracking' },
  { key: 'calendar', visual: 'a calendar page', use: 'scheduling, meetings, appointments, events' },
  { key: 'calendar-clock', visual: 'calendar with a clock', use: 'time management, deadlines, reminders' },
  { key: 'mail', visual: 'an envelope', use: 'email, correspondence, outreach, newsletters' },
  { key: 'chat', visual: 'a speech bubble', use: 'messaging, chat, conversations, communication' },
  { key: 'megaphone-loud', visual: 'a megaphone/bullhorn', use: 'marketing, announcements, campaigns, social media' },
  { key: 'data-trending', visual: 'upward trending line chart', use: 'analytics, reports, metrics, insights, dashboards' },
  { key: 'data-pie', visual: 'a pie chart', use: 'data visualization, breakdowns, analysis' },
  { key: 'chart-multiple', visual: 'multiple overlapping charts', use: 'reporting, business intelligence, KPIs' },
  { key: 'shield-checkmark', visual: 'shield with a checkmark', use: 'security, compliance, verification, audit' },
  { key: 'gavel', visual: 'a judges gavel', use: 'legal, contracts, court, arbitration' },
  { key: 'scales', visual: 'scales of justice', use: 'legal balance, fairness, compliance review' },
  { key: 'document-text', visual: 'a document with text lines', use: 'documents, writing, drafts, content creation' },
  { key: 'document-edit', visual: 'document with a pencil', use: 'editing, reviewing documents, proofreading' },
  { key: 'book-open', visual: 'an open book', use: 'knowledge base, documentation, wiki, learning' },
  { key: 'library', visual: 'shelves of books', use: 'reference library, archives, research repository' },
  { key: 'graduation-cap', visual: 'a graduation cap/mortarboard', use: 'training, education, courses, learning programs' },
  { key: 'lightbulb', visual: 'a light bulb', use: 'ideas, innovation, suggestions, brainstorming' },
  { key: 'briefcase', visual: 'a business briefcase', use: 'executive, management, business operations' },
  { key: 'building', visual: 'an office building', use: 'facilities, real estate, corporate, offices' },
  { key: 'globe', visual: 'a globe/earth', use: 'international, travel, global operations, localization' },
  { key: 'airplane', visual: 'an airplane', use: 'travel booking, flights, travel coordination' },
  { key: 'truck', visual: 'a delivery truck', use: 'logistics, shipping, delivery, supply chain' },
  { key: 'package', visual: 'a cardboard shipping box', use: 'fulfillment, orders, packages, warehouse' },
  { key: 'shopping-cart', visual: 'a shopping cart', use: 'e-commerce, orders, purchasing, procurement' },
  { key: 'code', visual: 'code brackets < / >', use: 'software development, coding, programming' },
  { key: 'wrench', visual: 'a wrench tool', use: 'maintenance, repairs, tools, configuration' },
  { key: 'settings', visual: 'a gear/cog', use: 'settings, configuration, system admin' },
  { key: 'search', visual: 'a magnifying glass', use: 'search, research, discovery, finding information' },
  { key: 'stethoscope', visual: 'a medical stethoscope', use: 'healthcare, medical, clinical, patient care' },
  { key: 'heart', visual: 'a heart shape', use: 'wellness, care, employee wellbeing, empathy' },
  { key: 'star', visual: 'a five-pointed star', use: 'ratings, favorites, quality, excellence' },
  { key: 'trophy', visual: 'a trophy cup', use: 'awards, recognition, achievements, competitions' },
  { key: 'rocket', visual: 'a rocket ship', use: 'launches, startups, growth, acceleration' },
  { key: 'sparkle', visual: 'sparkle/star shapes', use: 'AI, intelligence, magic, smart features' },
  { key: 'arrow-sync', visual: 'circular sync arrows', use: 'workflows, automation, processes, synchronization' },
  { key: 'lightning-bolt', visual: 'a lightning bolt', use: 'triggers, automation, speed, power' },
  { key: 'funnel', visual: 'a filter funnel', use: 'sales pipeline, filtering, data processing' },
  { key: 'handshake', visual: 'two hands shaking', use: 'partnerships, deals, vendor relations, agreements' },
  { key: 'hashtag', visual: 'a # hashtag symbol', use: 'social media, tagging, categorization' },
  { key: 'compass', visual: 'a navigation compass', use: 'strategy, direction, planning, guidance' },
  { key: 'design-ideas', visual: 'a lightbulb with sparkles', use: 'design, creative, UX/UI, visual work' },
  { key: 'paint-brush', visual: 'a paint brush', use: 'creative, art, design, branding' },
  { key: 'flag', visual: 'a flag on a pole', use: 'milestones, goals, flagging issues, priorities' },
  { key: 'target', visual: 'a bullseye target', use: 'goals, targeting, OKRs, objectives' },
  { key: 'lock-closed', visual: 'a padlock', use: 'security, privacy, access control, encryption' },
  { key: 'fingerprint', visual: 'a fingerprint', use: 'identity, authentication, biometrics' },
  { key: 'bot-sparkle', visual: 'a robot face with sparkles', use: 'AI assistant, chatbot, virtual agent' },
  { key: 'agents', visual: 'abstract agent shapes', use: 'general agent, default' },
  { key: 'ai-teammate', visual: 'teal-green circle with blue swirl — the AI Teammate logo', use: 'digital worker, AI teammate, digital coworker, digital employee' },
];

/** Format the icon catalog as a compact string for LLM prompts */
export function getIconCatalogPrompt(): string {
  return ICON_CATALOG.map(i => `${i.key}: ${i.visual} — ${i.use}`).join('\n');
}

/** Match a description to the best system color icon key using keyword scoring */
export function matchSystemColorIcon(description: string): string {
  const d = description.toLowerCase();
  const rules: [string[], string][] = [
    [['sales', 'crm', 'deal', 'revenue', 'pipeline', 'quota'], 'coin-multiple'],
    [['customer', 'client', 'support', 'service', 'help desk', 'ticket'], 'headset'],
    [['hr', 'human resources', 'hiring', 'recruit', 'onboard'], 'people-team'],
    [['finance', 'accounting', 'invoice', 'budget', 'expense', 'payment'], 'receipt'],
    [['legal', 'compliance', 'contract', 'policy', 'regulation'], 'shield-checkmark'],
    [['marketing', 'campaign', 'brand', 'social media', 'content'], 'megaphone-loud'],
    [['project', 'task', 'sprint', 'agile', 'kanban', 'backlog'], 'clipboard-task'],
    [['design', 'creative', 'figma', 'ux', 'ui'], 'design-ideas'],
    [['code', 'develop', 'engineer', 'programming', 'devops', 'deploy'], 'code'],
    [['data', 'analytics', 'report', 'dashboard', 'metric', 'insight'], 'data-trending'],
    [['email', 'mail', 'inbox', 'outlook', 'correspondence'], 'mail'],
    [['document', 'doc', 'write', 'edit', 'draft', 'content'], 'document-text'],
    [['meeting', 'schedule', 'calendar', 'agenda', 'appointment'], 'calendar'],
    [['chat', 'message', 'conversation', 'teams', 'slack', 'communicate'], 'chat'],
    [['search', 'find', 'lookup', 'discover', 'research'], 'search'],
    [['security', 'protect', 'guard', 'monitor', 'threat', 'audit'], 'shield'],
    [['knowledge', 'wiki', 'faq', 'documentation', 'library'], 'book-open'],
    [['train', 'learn', 'education', 'course', 'tutorial', 'graduation', 'school'], 'graduation-cap'],
    [['health', 'medical', 'patient', 'clinical', 'wellness', 'doctor', 'hospital', 'diagnosis', 'stethoscope', 'healthcare'], 'stethoscope'],
    [['shipping', 'logistics', 'supply chain', 'warehouse', 'delivery'], 'truck'],
    [['travel', 'trip', 'booking', 'flight', 'hotel'], 'globe'],
    [['real estate', 'property', 'building', 'facility'], 'building'],
    [['order', 'cart', 'checkout', 'purchase', 'transaction'], 'shopping-cart'],
    [['retail', 'store', 'shop', 'ecommerce', 'product'], 'building-store'],
    [['workflow', 'automat', 'process', 'orchestrat'], 'arrow-sync'],
    [['ai', 'intelligent', 'smart', 'copilot', 'assistant'], 'sparkle'],
    [['team', 'collaborat', 'group', 'department'], 'people'],
    [['person', 'employee', 'staff', 'individual', 'user'], 'person'],
    [['manage', 'lead', 'supervise', 'director', 'executive'], 'briefcase'],
  ];
  let bestKey = 'agents';
  let bestScore = 0;
  for (const [keywords, key] of rules) {
    let score = 0;
    for (const kw of keywords) {
      if (d.includes(kw)) score++;
    }
    if (score > bestScore) {
      bestScore = score;
      bestKey = key;
    }
  }
  return bestKey;
}
