// ─── Connector registry (sourced from Power Automate connector reference) ──
// Extracted to its own file due to size (~800 connector names).

export const CONNECTORS = [
  '10to8 Appointment Scheduling', '1DocStop', '1Me Corporate', '1pt', '24 pull request', '365 Training', '3E Events', '9A Raptor Document Warehouse',
  'Abbreviations', 'Abortion Policy', 'absentify', 'Abstract Company Enrichment', 'Abstract Email Validator', 'Abstract Exchange Rates', 'Abstract Holidays',
  'Abstract IBAN Validator', 'Abstract IP Geolocation', 'Abstract Phone Validator', 'Abstract Timezones', 'Abstract VAT Validator', 'AccuWeather', 'Act!',
  'ActivityInfo', 'Acumatica', 'Address Labs', 'Adobe Acrobat Sign', 'Adobe Acrobat Sign Sandbox', 'Adobe Creative Cloud', 'Adobe Experience Manager',
  'Adobe PDF Services', 'Advanced Data Operations', 'Advanced Scraper', 'Affirmations', 'Africa\'s Talking Airtime', 'Africa\'s Talking SMS', 'Africa\'s Talking Voice',
  'AfterShip', 'AgilePoint NX', 'Agilite', 'Ahead', 'Ahead (Intranet)', 'AI or Not', 'AIForged', 'AIHW MyHospitals', 'AikiDocs', 'Airlabs', 'Airly', 'Airmeet',
  'airSlate', 'Airtable', 'Alemba ITSM', 'Aletheia', 'AlisQI', 'Alkymi', 'allGeo', 'Ally', 'Almabase', 'Almanac', 'ALVAO',
  'Amazon Redshift', 'Amazon S3', 'Amazon S3 Bucket', 'Amazon SQS', 'Ambee', 'AMEE Open Business', 'Annature', 'Ant Text Automation', 'Anthropic',
  'ANY.RUN Threat Intelligence', 'Apache Impala', 'APITemplate', 'APlace.io', 'App Power Forms', 'App Store Connect - App Store', 'Appfigures',
  'AppsForOps Timeline', 'Apptigent PowerTools', 'Apptigent PowerTools LITE', 'ApyHub', 'ApyHub Document Readability', 'ApyHub Generate iCal',
  'Aquaforest PDF', 'Aranda Service Management', 'ArcGIS', 'ArcGIS Enterprise', 'ArcGIS PaaS', 'Asana', 'Asite', 'Asite (Canada)', 'Asite (Hong Kong)',
  'Asite (KSA)', 'Asite (UAE)', 'Asite (US Gov.)', 'ASPSMS', 'AssemblyAI', 'Assently E-Sign', 'AtBot Admin', 'AtBot Logic', 'Autenti E-Signature Workflow',
  'Autodesk Data Exchange', 'AutoReview', 'AutoSeller', 'AvePoint Cloud Governance', 'Aviationstack', 'AWeber',
  'Azure AD Identity and Access', 'Azure AI Document Intelligence (form recognizer)', 'Azure AI Foundry Agent Service', 'Azure AI Foundry Inference',
  'Azure AI Search', 'Azure App Service', 'Azure Application Insights', 'Azure Automation', 'Azure Batch Speech-to-text', 'Azure Blob Storage',
  'Azure Cognitive Service for Language', 'Azure Communication Chat', 'Azure Communication Email', 'Azure Communication Services Identity',
  'Azure Communication Services SMS', 'Azure Communication Services SMS Events', 'Azure Confidential Ledger', 'Azure Container Instance', 'Azure Cosmos DB',
  'Azure Data Explorer', 'Azure Data Factory', 'Azure Data Lake', 'Azure Database for MySQL', 'Azure Databricks', 'Azure DevOps', 'Azure Digital Twins',
  'Azure Event Grid', 'Azure Event Grid Publish', 'Azure File Storage', 'Azure IoT Central V2', 'Azure IoT Central V3', 'Azure Key Vault',
  'Azure Log Analytics', 'Azure Log Analytics Data Collector', 'Azure Monitor Logs', 'Azure OpenAI', 'Azure Queues', 'Azure Resource Manager',
  'Azure Speech Pronunciation Assessment', 'Azure SQL Data Warehouse', 'Azure Table Storage', 'Azure Text to speech', 'Azure VM',
  'Badgr', 'Basecamp 2', 'Basecamp 3', 'BBC News', 'Beauhurst', 'Benchmark Email', 'Benifex', 'Bigdata-com', 'BillsPLS', 'BIN Checker',
  'Binance.us', 'Bing Maps', 'Bing Search', 'Bitbucket', 'Bitly', 'BitlyIP', 'Bitskout', 'Bitvore Cellenus', 'BizTalkServer', 'BKK Futar',
  'Blackbaud Altru Constituent', 'Blackbaud Church Management', 'Blackbaud CRM Constituent', 'Blackbaud CRM Prospect',
  'Blackbaud FENXT General Ledger', 'Blackbaud FENXT Payable', 'Blackbaud FENXT Query', 'Blackbaud Raisers Edge NXT',
  'Blackbaud Raisers Edge NXT Constituents', 'Blackbaud Raisers Edge NXT Documents', 'Blackbaud Raisers Edge NXT Events',
  'Blackbaud Raisers Edge NXT Fundraising', 'Blackbaud Raisers Edge NXT Interactions', 'Blackbaud Raisers Edge NXT Lists',
  'Blackbaud Raisers Edge NXT Prospects', 'Blackbaud RENXT Gifts', 'Blackbaud RENXT Query', 'Blackbaud RENXT Reports', 'Blackbaud SKY Add-ins',
  'Blogger', 'Bloomflow', 'BlueInk', 'Bluesky Social', 'BoldSign', 'boomapp connect', 'Box', 'Box MCP Server', 'Brave Search', 'bttn', 'Bttn ONE',
  'Buffer', 'BuildingMinds DigitalTwin Core', 'BulkSMS', 'Bureau of Labor Statistics', 'Business Assist', 'Businessmap', 'Buy Me A Coffee', 'Buzz', 'Byword',
  'Calculate Working Day', 'Calendar Pro', 'Calendarific', 'Calendly', 'Calendly (legacy)', 'Campfire', 'CandidateZip Resume/Job Parser', 'Capsule CRM',
  'Captisa Forms', 'Carbon Intensity', 'CarbonFootprint', 'CardPlatform Adaptive Cards', 'CarsXE', 'Cascade', 'Cascade Strategy New',
  'Casper365 for Education', 'CB Blockchain Seal', 'CData Connect AI', 'CDC Content Services', 'CDK Drive Customer', 'CDK Drive Service Vehicles',
  'Celonis', 'Celonis MCP Server', 'Centrical', 'Certinal eSign', 'Certopus', 'CGTrader', 'Chainpoint', 'Chatter', 'Checkly', 'Chuck Norris IO',
  'cioplenu', 'Cireson Service Manager Portal', 'Cisco Webex Meetings', 'Citymapper', 'CivicPlus Transform', 'Clearbit', 'CleverTap',
  'ClickSend', 'ClickSend Postcards', 'ClickUp Team Manager', 'Climatiq', 'Clinical Trials', 'Clockify', 'Cloud BOT', 'Cloud Connect Studio',
  'Cloud PKI Management', 'CloudConvert', 'Cloudmersive Barcode', 'Cloudmersive CDR', 'Cloudmersive Currency', 'Cloudmersive Data Validation',
  'Cloudmersive Document Conversion', 'Cloudmersive File Processing', 'Cloudmersive Image Processing', 'Cloudmersive NLP', 'Cloudmersive PDF',
  'Cloudmersive Security', 'Cloudmersive Video and Media', 'Cloudmersive Virus Scan', 'CloudTools for Salesforce', 'Cloverly', 'CluedIn', 'CMI',
  'CO2 Signal', 'CobbleStone - Contract Insight', 'Cognito Forms', 'Cognizant Automation Center', 'Cohere', 'Coinbase', 'Commercient',
  'Companies House', 'Company Connect', 'Composer by Tachytelic', 'Computer Vision API', 'Confluence', 'Connect2All', 'Connect2All on-premises',
  'Connective eSignatures', 'ConnectWise PSA', 'connpass', 'ConsenSys Ethereum', 'Contacts Pro', 'Content Conversion', 'Content Gate',
  'Content Manager Power Connect', 'Content Moderator', 'Contoso Hub', 'Converter by Power2Apps', 'ConvertKit', 'Copilot for Finance',
  'Copilot for Sales', 'Copilot for Service extension', 'Copy.ai', 'Corda Blockchain', 'Cornerstone Learning vILT', 'Corporate Buzzword Generator',
  'COSMO Bot', 'Coupa', 'Courier', 'COVID-19 JHU CSSE', 'CPQSync', 'CPSC Recalls Retrieval', 'CQC Data', 'Cradl AI', 'CraftMyPDF', 'CRM Bot',
  'Crossbeam', 'CSV Converter by Power2Apps', 'Custom Vision', 'CustomJS', 'CX Cards by Surveyapp', 'Cyberday', 'CyberProof',
  'D&B Optimizer', 'd.velop', 'D365 Contact Center Admin MCP', 'D7Messaging', 'D7SMS', 'Dad Jokes', 'DadJokesIO', 'Daffy', 'DailyMed', 'Dandelion',
  'Data Activator', 'Data Activator Early Access', 'Data8 Data Enrichment', 'Datablend', 'Databook C4S', 'Databox', 'Databricks', 'DataMotion',
  'Datamuse', 'DataScope Forms', 'DB2', 'DBF2XML', 'De Lijn', 'Decentraland', 'Deck of Cards', 'Deepgram', 'DeepL', 'DeepLIP', 'DeepSign',
  'Defender for Cloud Apps', 'Derdack SIGNL4', 'Desk365', 'DeskDirector', 'Desktop flows', 'Dexcom', 'DiceBear', 'Did You Mean This',
  'Diffchecker', 'DigiDates', 'DigiLEAN Connect', 'DigitalHumani', 'Dime.Scheduler', 'Dime.Scheduler (on-prem)', 'Discord', 'Disqus',
  'Do Not Call Reported Calls', 'Doc To PDF', 'DocFusion365 – SP', 'DocJuris', 'Docparser', 'Docugami', 'DocuGenerate', 'Document AI',
  'Document AI Konfuzio', 'Document Drafter', 'Document Merge', 'Documentero', 'DocumentsCorePack', 'DocuMotor', 'Docurain', 'Docusign',
  'Docusign Demo', 'DocuWare', 'Dokobit Portal', 'Dokobit Universal API', 'DomainTools Iris Enrich', 'DomainTools Iris Investigate',
  'Doppler Farhan Latif', 'dox42', 'DPIRD Radar - West Australia', 'DPIRD Science - West Australia', 'DPIRD Weather - West Australia',
  'DQ on Demand', 'Draup', 'Draup MCP Server', 'Dropbox', 'Duration Calculator', 'DVLA Vehicle Enquiry Service', 'Dynamic Signal', 'DynamicDocs',
  'Dynamics 365 Business Central', 'Dynamics 365 Business Central (on-premises)', 'Dynamics 365 Commerce - Ratings and Reviews',
  'Dynamics 365 Commerce Merchandising', 'Dynamics 365 Customer Insights', 'Dynamics 365 Customer Voice', 'Dynamics 365 Fraud Protection',
  'Dynamics 365 Sales Insights', 'Dynamics NAV', 'Dynamics Translation Service', 'Dynatrace',
  'Easy Redmine', 'EasyPost Mail', 'Easyship', 'Easyvista Self Help', 'EasyVista Service Manager', 'eBay', 'EBMS', 'eCFR', 'Ecologi',
  'edatalia Sign Online', 'Eden AI', 'Edgility', 'Eduframe', 'Egain', 'Egnyte', 'E-goi', 'Eigen Events', 'Elastic Forms', 'ElasticOCR',
  'Elead Product Reference Data', 'Elead Sales Customers', 'Elead Sales Opportunities', 'Electricity Maps', 'Elfsquad Data',
  'Elfsquad Product Configurator', 'Email Domain Checker', 'Email Veritas – URL Checker', 'emfluence Marketing Platform', 'Emigo', 'EmojiHub',
  'EMT ATLAS AIMS', 'Enadoc', 'Encodian', 'Encodian - Barcode', 'Encodian - Convert', 'Encodian - Excel', 'Encodian - General',
  'Encodian - Image', 'Encodian - PDF', 'Encodian - PowerPoint', 'Encodian - Utilities', 'Encodian - Word', 'Encodian Filer', 'Encodian Trigr',
  'Engagement Cloud', 'Enlyft Insights', 'Enlyft MCP', 'Entegrations.io', 'Entersoft', 'Enveloop', 'Envoy', 'EONET by NASA',
  'Ephesoft Semantik For Invoices', 'E-Sign', 'Ethereum Blockchain', 'Etsy', 'Event Hubs', 'Event Tickets', 'Eventbrite', 'Every',
  'Evocom', 'eWay-CRM', 'Exact Online Premium', 'Exact Time & Billing', 'Exasol', 'Excel', 'Excel Online (Business)', 'Excel Online (OneDrive)',
  'Exchange Rate', 'Expensya', 'Experlogix CPQ', 'Experlogix Smart Flows', 'Expiration Reminder', 'EXPOCAD',
  'Face API', 'FactSet', 'Fantasy Premier League', 'Farsight DNSDB', 'FBI Most Wanted', 'FCA', 'Feathery', 'Feathery Forms',
  'Federal Reserve Economic Data', 'Federal Reserve Markets', 'FEMA', 'Festivo', 'FHIRBase', 'FHIRClinical', 'FHIRlink', 'FieldEquip',
  'File System', 'File.io', 'Files.com', 'Finalcad One Connect 4.0', 'Financial Edge NXT Query', 'Finnish BIS', 'Finnish Railway Traffic',
  'FINRA', 'FireText', 'Fiscal Data Service', 'FishWatch', 'Fitbit', 'Flic', 'Fliplet', 'Flotiq headless CMS', 'FlowForma', 'FlowForma V2',
  'Focusmate', 'FORCAM FORCE Bridge', 'ForceManager CRM', 'Forem', 'Formstack Documents', 'Formstack Forms', 'FraudLabs Pro', 'FreeAgent',
  'FreshBooks', 'Freshdesk', 'Freshservice', 'FTP', 'Fun Translations',
  'Generative actions', 'GeoDB', 'German Federal Parliament', 'GetAccept', 'GetMyInvoices', 'Gieni TS Server MCP', 'GIPHY', 'GIS Cloud',
  'GitHub', 'Github Data', 'GitHub Gists', 'GitHub Utils', 'GitLab', 'Givebutter', 'Glaass Pro', 'Global Exchange Rates', 'GlobalGiving Project',
  'Gmail', 'GMO Sign', 'GoFileRoom', 'Google BigQuery', 'Google Books', 'Google Calendar', 'Google Cloud Translation', 'Google Contacts',
  'Google Drive', 'Google Gemini', 'Google PaLM', 'Google Photos', 'Google Sheets', 'Google Tasks', 'GoQR', 'GoToMeeting', 'GoToTraining',
  'GoToWebinar', 'Govee', 'Gratavid', 'Gravity Forms by reenhanced', 'Gravity Forms Professional', 'Groopit', 'GroupMgr',
  'GSA Analytics', 'GSA Per Diem', 'GSA Public Comment', 'GSA Site Scanning',
  'Harness PDFx', 'Harvest', 'Hash Generator', 'Hashify', 'Hashtag API', 'Have I Been Pwned', 'HelloSign', 'HHS Media Services',
  'HighGear Workflow', 'HighQ', 'Highspot', 'Highspot MCP', 'HipChat', 'HitHorizons', 'Hive CPQ Product Configurator', 'Holopin',
  'Honeywell Forge', 'Host.io', 'HotProfile', 'Houdin.io', 'HouseRater QA', 'HR Cloud', 'HrFlow.ai', 'HTML to PDF by Pascalcase',
  'HTTP With Microsoft Entra ID', 'HTTP with Microsoft Entra ID (preauthorized)',
  'HubSpot CMS', 'HubSpot CMS V2', 'HubSpot Conversations V2', 'HubSpot CRM', 'HubSpot CRM V2', 'HubSpot Engagements V2',
  'HubSpot Files V2', 'HubSpot Marketing', 'HubSpot Marketing V2', 'HubSpot Settings V2', 'Huddle', 'Huddle for US Gov & Healthcare',
  'Huddo Boards', 'HUE Datagate', 'Hugging Face', 'Hume', 'Hunter', 'HVI Vehicle Inspection V1.2', 'HYAS Insight',
  'IA-Connect Dynamic Code', 'IA-Connect Java', 'IA-Connect JML', 'IA-Connect Mainframe', 'IA-Connect SAP GUI', 'IA-Connect Session',
  'IA-Connect to Microsoft Office', 'IA-Connect UI', 'IA-Connect Web Browser', 'iAuditor', 'IBM Watson Assistant', 'IBM Watson Text to Speech',
  'icanhazdadjoke', 'Icon Horse', 'ID Analyzer', 'Ideanote', 'iFacto Proof Of Delivery', 'iLovePDF', 'iLoveSign', 'iManage AI',
  'iManage Data Marts', 'iManage Insight Plus', 'iManage Tracker', 'iManage Work', 'iManage Work for Admins', 'iMIS', 'Impexium',
  'Impower ERP', 'Imprezian360-CRM', 'IN-D Aadhaar Number Masking', 'IN-D Face Match', 'IN-D Insurance (ICD10 & CPT)',
  'IN-D Invoice Data Capture', 'IN-D KYC India', 'IN-D Payables', 'Industrial App Store', 'InEight', 'Influenza and Covid-19',
  'Infobip', 'InfoQuery', 'Informix', 'InfoShare', 'InfoVetted', 'Infura Ethereum', 'Infusionsoft', 'InLoox', 'Inoreader',
  'inQuba Journey', 'Insightly', 'Instagram Basic Display', 'Instapaper', 'Instatus', 'Integrable PDF', 'Integration Toolbox',
  'Intelix IOC Analysis MCP', 'intelliHR', 'Intentional Data Sources', 'InterAction', 'Intercom', 'iObeya',
  'IP2LOCATION', 'IP2WHOIS', 'IPQS Fraud and Risk Scoring', 'IQAir', 'ISOPlanner', 'ITautomate', 'ITGlue',
  'Jasper', 'JBHunt', 'Jedox OData Hub', 'JG Integrations', 'Jira', 'JIRA Search', 'JotForm', 'Jotform Enterprise', 'Jservice',
  'JungleMail 365', 'Jupyrest',
  'K2 Workflow', 'Kagi', 'Kanban Tool', 'kintone', 'KnowledgeLake', 'Knowledgeone RecFind6', 'KORTO V2', 'Kroki', 'Krozu PM', 'Kyndryl mainframe',
  'Lang.ai', 'Language - Question Answering', 'Lansweeper App For Sentinel', 'Lasso X', 'LatinShare Documents', 'LatinShare SHP Management',
  'LatinShare SHP Permissions', 'Launch Library 2', 'Lawlift', 'LawVu', 'LCP - iCordis', 'LeadDesk', 'LeanKit', 'Leap', 'Leave Dates',
  'LegalBot AI Tools', 'Legalesign', 'LegiScan', 'Letterdrop', 'Lettria', 'Lettria GDPR Compliance', 'Lex Power Sign', 'Lexica',
  'Lexoffice', 'Library of Congress', 'LibreBor', 'LIFX', 'Line Message', 'LINK Mobility', 'LinkedIn', 'LinkedIn V2', 'Lit Ipsum',
  'Litera Search', 'LiveChat', 'LiveTiles Bots', 'LMS365', 'Lnk.Bio', 'LoginLlama', 'Loopio', 'Loopio-EU', 'Loopio-Int01', 'Loripsum',
  'LSEG', 'LSEG Financial Analytics', 'LUIS', 'Luware Nimbus',
  'M365 Search', 'Maersk', 'Mail', 'MailboxValidator', 'MailChimp', 'Mailform', 'Mailinator', 'MailJet', 'MailParser',
  'Maintenance Request - Oxmaint', 'Mandrill', 'Map Pro', 'Mapbox', 'Markdown Converter', 'Marketing Content Hub', 'Marketo MA',
  'Mavim-iMprove', 'Maximizer CRM', 'MCP Hive.T Integration', 'MeaningCloud', 'Medallia', 'Mediastack', 'Medium', 'Meekou Share',
  'MeetingRoomMap', 'Meisterplan', 'Meme', 'Mensagia', 'MessageBird SMS', 'Metatask', 'Michael Scott Quotes',
  'Microsoft 365 Compliance', 'Microsoft 365 Message Center', 'Microsoft 365 Self-Help', 'Microsoft Acronyms', 'Microsoft Bookings',
  'Microsoft Copilot Studio', 'Microsoft D365CE v9 OnPrem', 'Microsoft Defender ATP', 'Microsoft Entra ID',
  'Microsoft Entra ID App Registrations', 'Microsoft Entra ID Protection', 'Microsoft Forms', 'Microsoft Graph Add Users',
  'Microsoft Graph Security', 'Microsoft Kaizala', 'Microsoft Learn Catalog', 'Microsoft Learn Docs MCP', 'Microsoft Loop',
  'Microsoft Partner Center', 'Microsoft School Data Sync V2', 'Microsoft Security Copilot', 'Microsoft Sentinel MCP',
  'Microsoft Teams', 'Microsoft To-Do (Business)', 'Microsoft To-Do (Consumer)', 'Microsoft Translator V2', 'Microsoft Translator V3',
  'Mime Automation', 'MiniSoup HTML Parser', 'Mintlify', 'MintNFT', 'Miro', 'Mistral', 'Mitto', 'MobilyWS', 'MOBSIM Send SMS',
  'Mockaroo', 'Mockster', 'ModuleQ', 'monday', 'monday.com', 'MongoDB', 'Monster API', 'Moosend', 'MoreApp Forms', 'Morf',
  'Morningstar', 'Morta', 'MotaWord Translations', 'Motimate', 'MS Graph Groups and Users', 'MSN Weather', 'Mtarget SMS',
  'Muhimbi PDF', 'MURAL', 'My Acclaro', 'My Hours', 'MySQL', 'myStrom',
  'N-able Cloud Commander', 'N-able Cloud User Hub', 'NameAPI', 'Narvar', 'NASA FIRMS', 'NASA Image and Video Library',
  'National Park Service', 'National Weather Service', 'Nationalize_io', 'nBold', 'NCEI Climate Data', 'Nederlandse Spoorwegen',
  'NEOWs', 'NetDocuments', 'Netvolution', 'Neum', 'New York Times', 'NewsData.io', 'Nexmo', 'Nextcom', 'NH360 Portfolio Insights',
  'NHTSA vPIC', 'Nifty Gateway', 'Nimflow', 'Nintex Workflow', 'NIST NVD', 'Nitro', 'Nitro Sign Enterprise Verified',
  'Nodefusion Portal', 'Nosco', 'Notifications', 'Notiivy Browser Notifications', 'Notion', 'Noxtua AI', 'Nozbe', 'nps.today', 'NREL',
  'NumlookupAPI', 'nunify', 'Nutrient - Convert to PDF', 'Nutrient - Extract from PDF', 'Nutrient - PDF OCR', 'Nutrient - Watermark to PDF',
  'Nutrient Document Converter', 'Nutrient Workflow Automation',
  'Objective Connect', 'Occuspace', 'Office 365 Groups', 'Office 365 Groups Mail', 'Office 365 Outlook', 'Office 365 Users',
  'Office 365 Video', 'OfficeAi Agent', 'OK dokument', 'OMDb', 'oncehub', 'OneBlink', 'OneDrive', 'OneDrive for Business',
  'Oneflow', 'OneNote (Business)', 'OneNote Consumer', 'OnePlan', 'One-Time Secret', 'Oodrive Sign', 'Open Brewery DB', 'Open Charge Map',
  'Open Experience', 'OpenAI', 'OpenAI Assistants', 'OpenAI GPT', 'OpenCage Geocoding', 'Open-Elevation', 'openFDA Drug', 'OpenFEC',
  'OpenLegacy IBM I (AS400)', 'OpenLegacy IBM Mainframe', 'OpenNEM', 'OpenPLZ', 'openpm', 'OpenQR', 'OpenRouter', 'OpenSanctions',
  'OpenText Core Share', 'OpenText Documentum', 'OpenText eDOCS', 'OpenText Extended ECM', 'OpenTrivaDatabase', 'OptiAPI', 'OQSHA',
  'Oracle Database', 'ORB Intelligence', 'OrbusInfinity', 'Ordnance Survey Places', 'Originality.AI', 'Otto.bot', 'Outlook Tasks', 'Outlook.com',
  'Outreach Insights', 'Owlbot',
  'PagePixels Screenshots', 'PagerDuty', 'Pantry', 'Panviva', 'Pappers', 'ParishSoft Family Suite', 'Parserr', 'Parseur',
  'Partner Center Events', 'Partner Center Referrals', 'PartnerLinq', 'Passage by 1Password - Auth', 'Passage by 1Password - Manage',
  'Paylocity', 'PaySpace', 'PDF Blocks', 'PDF Tools', 'PDF4me', 'PDF4me AI', 'PDF4me Barcode', 'PDF4me Connect', 'PDF4me Convert',
  'PDF4me Excel', 'PDF4me Image', 'PDF4me PDF', 'PDF4me SwissQR', 'PDF4me Word', 'PDFco', 'PDFcross', 'Pdfless', 'Peakboard',
  'Peltarion AI', 'Perfect Wiki', 'Perplexity AI', 'Personr', 'Pexels', 'Philips HUE', 'Pilot Things', 'Pinecone', 'Pinterest',
  'Pipedrive', 'Pipeliner CRM', 'PIPware KPIs', 'Pitney Bowes Data Validation', 'Pitney Bowes Tax Calculator', 'Pivotal Tracker',
  'Pixel Encounter', 'Pixela', 'PixelMe', 'PKIsigning', 'Placedog', 'Planful', 'Planner', 'Pling', 'Plivo', 'Plumsail Actions',
  'Plumsail Documents', 'Plumsail Forms', 'Plumsail HelpDesk', 'Poka', 'PokeAPI Core', 'PokeAPI World', 'Polaris PSA', 'PoliteMail',
  'Polygon', 'Portfolio and Roadmap', 'PostgreSQL', 'Postman', 'Powell Teams', 'Power Apps for Admins', 'Power Apps for Makers',
  'Power Apps Notification', 'Power Apps Notification V2', 'Power Assist', 'Power Automate for Admins', 'Power Automate Management',
  'Power BI', 'Power Form 7', 'Power Platform for Admins', 'Power Platform for Admins V2', 'Power Query Dataflows', 'Power Textor',
  'Power Virtual Agents', 'PPM Express', 'Preserve365', 'PrexView', 'Priority Matrix', 'Priority Matrix HIPAA', 'Priva',
  'Process Mining', 'Process Street', 'Process Street MCP Server', 'Profisee', 'Progressus Advanced Projects', 'Project Online',
  'ProjectPlace', 'Projectum Present It', 'ProjectWise Design Integration', 'Projectwise Share', 'ProPublica Campaign Finance',
  'ProPublica Congress', 'ProPublica Nonprofit Explorer', 'PROS AI', 'Public 360', 'PUG Gamified Engagement', 'Pure Leads',
  'Pushcut', 'Pushover',
  'Qdrant', 'QnA Maker', 'QPP NextGen', 'Quickbase', 'QuickBooks Time', 'QuickChart',
  'Rainbird', 'RamQuest Actions', 'RamQuest Events', 'RAPID Platform', 'Rarible', 'Reachability', 'Readwise',
  'RealFaviconGenerator', 'Rebrandly', 'Rebrickable', 'Receptful', 'Recorded Future', 'Recorded Future Identity',
  'Recorded Future Sandbox', 'Recorded Future V2', 'Redmine', 'Redque', 'Reflect', 'Refuge Restrooms', 'RegEx Matching',
  'RegexFlow ExecutePython', 'RegexFlow Regular Expression', 'RegoLink for Clarity PPM', 'ReliefWeb', 'Rencore Code',
  'Rencore Governance', 'Repfabric', 'Repfabric Job Loader', 'Repfabric Lead Loader', 'Replicate', 'Replicon', 'Requestor',
  'Resco Cloud', 'Resco Reports', 'RescueGroups', 'Resend', 'REST Countries', 'Retarus SMS', 'Rev AI', 'Revelation helpdesk',
  'ReversingLabs A1000', 'Revue', 'Rijksmuseum', 'Rijksoverheid', 'RiskIQ', 'RiskIQ Digital Footprint', 'RiskIQ Illuminate',
  'Robohash', 'Robolytix', 'Robots for Power BI', 'Ron Swanson Quotes', 'RowShare', 'RSign', 'RSS',
  'Salesforce', 'SAP ERP', 'SAP OData', 'Sapling.ai', 'SAS Decisioning', 'ScanCloud', 'Schiphol Airport', 'SchoolDigger',
  'ScrapingBee', 'Screenshot One', 'Scrive eSign', 'Scryfall', 'SearchAPI - Google Search', 'SECIB', 'Secret Server',
  'Secure Code Warrior', 'SeeBotRun - Link', 'SeekTable', 'Seismic', 'Seismic Configuration', 'Seismic Content Discovery',
  'Seismic Engagement', 'Seismic for Copilot for Sales', 'Seismic Library', 'Seismic Livedoc', 'Seismic Planner',
  'Seismic Programs', 'Seismic Workspace', 'SendFox', 'SendGrid', 'Sendmode', 'Serverless360 BAM & Tracking', 'Service Bus',
  'Service Objects', 'ServiceDesk Plus Cloud', 'ServiceNow', 'SerwerSMS', 'Sessionize', 'SFTP', 'SFTP - SSH', 'Shadify',
  'Share-Effect', 'SharePoint', 'SharePoint Embedded', 'Sherpa Digital', 'Shields.io', 'Shifts for Microsoft Teams',
  'ShipStation IP', 'Shop', 'Shopify', 'Shopranos', 'Short URL', 'ShortySMS', 'Showcase Workshop', 'Showpad eOS', 'SHRTCODE',
  'Sigma Conso CR', 'SignatureAPI', 'Signhost', 'Signi.com', 'SigningHub', 'SIGNL4 - Mobile Alerting', 'SignNow', 'SignNow EU',
  'SignRequest', 'SignUpGenius', 'Simple EDI', 'SimpleSurvey', 'Sinch', 'Sirva Relocating Employee', 'Skribble Sign',
  'Skype for Business Online', 'SkyPoint Cloud', 'Slack', 'Slascone', 'smapOne', 'Smarp', 'SmartCOMM DocGen', 'SmartDialog',
  'Smarter Drafter', 'Smartsheet', 'SmileBack', 'SMS Wireless Services', 'sms77io', 'SMSAPI', 'SMSLink', 'SMTP', 'Snowflake',
  'Sociabble', 'Socialinsider', 'Soft1', 'Softone Web CRM', 'Softools', 'SolarEdge', 'SoloSign HMAC Hash Creator',
  'SOS Inventory', 'SparkPost', 'Sparse Power Box Tools', 'Spinpanel', 'Spoonacular Food', 'Spoonacular Meal Planner',
  'Spoonacular Recipe', 'Spotify', 'Spring Global', 'SQL Server', 'Square Business', 'Square Payments', 'Stability.ai',
  'Staffbase', 'StaffCircle', 'Standard approvals', 'Star Wars', 'Starmind', 'StarRez REST v1', 'Storm Glass', 'Stormboard',
  'Straker Verify', 'Strava', 'Stripe', 'Studio Ghibli', 'Sunrise-Sunset', 'SuperMCP', 'Supportivekoala', 'SureXeroLite',
  'Survalyzer EU', 'Survalyzer Swiss', 'Survey123', 'SurveyMonkey', 'SurveyMonkey Canada', 'Swagger Converter', 'Synthesia',
  'T.LY', 'Tabscanner Receipt OCR', 'TAGGUN Receipt OCR Scanning', 'Tago', 'Taktikal Core', 'Talkdesk', 'Tallyfy', 'TALXIS Data Feed',
  'Taqnyat', 'Tavily', 'Tax ID Pro', 'TDox', 'Team Forms', 'Teamflect', 'Teams-Spirit', 'TeamWherx', 'Teamwork Projects',
  'tegolySIGN', 'Telegram Bot', 'Telephony Xtended Serv Interf', 'TeleSign SMS', 'Templafy', 'Tendocs Documents', 'Teradata',
  'Tesseron Asset Management', 'Tesseron Basic Data', 'Tesseron Invoice', 'Tesseron Ticket', 'Text Analytics', 'Text Request',
  'The Bot Platform', 'The Brønnøysund Registries', 'The Color', 'The Events Calendar', 'The Guardian', 'The IT Tipster',
  'The Lord of the Rings', 'The SMS Works', 'The Weather Channel', 'TheGoodAPI', 'TheMealDB', 'Threads', 'Ticketing.events',
  'Ticketmaster', 'Tikit', 'Tiliter Vision Agents', 'Tilkee', 'TimeAPI', 'timeghost', 'Timeneye', 'TLDR', 'Today in History',
  'Todoist', 'Toggl Plan', 'Toggl Track', 'Tomorrow.io', 'Toodledo', 'Tophhie Cloud', 'TopMessage', 'touchSMS', 'TPC Portal',
  'Traction Guest', 'Trade.Gov', 'Transform2All', 'Tree-Nation', 'Trello', 'Tribal - Maytas', 'Tribal - Platform', 'Tribal - SITS',
  'TRIGGERcmd', 'Trovve', 'TrueDialog SMS', 'Trustual', 'Tulip', 'Tumblr', 'TuxMailer', 'Twilio', 'TxtSync',
  'tyntec 2FA', 'tyntec Phone Verification', 'tyntec SMS Business', 'tyntec Viber Business', 'tyntec WhatsApp Business', 'Typeform',
  'U.S. Bank Treasury Management', 'Uber Freight', 'Ubiqod by Skiply', 'Ubiqod by Taqt', 'Udemy', 'UiPath', 'UiPath Orchestrator',
  'UK Bank Holidays', 'UK Check VAT', 'UKG Pro HCM', 'UKG PRO WFM Authentication', 'UKG Pro WFM Employee', 'UKG Pro WFM People',
  'UKG Pro WFM Timekeeping', 'Unix Timestamp', 'Unofficial Netflix Search', 'Unsplash', 'Updates App (Microsoft 365)', 'Updown',
  'Upland Panviva US', 'URL.dev', 'UrLBae', 'US Congress CRS', 'US Patent & Trademark Office', 'USAJOBS', 'USB4SAP',
  'UserVoice', 'USGS Earthquake Hazards',
  'Vantage 365 Imaging', 'Varuna', 'vatcheckapi', 'Vena Solutions', 'Ventipix Asset and Inventory', 'Verified',
  'Veteran Confirmation', 'Veterans Affairs Facilities', 'Veterans Affairs Forms', 'Veterans Affairs Providers', 'Viafirma',
  'Video Indexer (V2)', 'VIES', 'Vimeo', 'Virtual Data Platform', 'Virus Total', 'Viva Engage', 'Vocean', 'Voice Monkey',
  'VoiceRSS', 'Vome', 'Vonage',
  'Waaila', 'Way We Do', 'Wayback Machine', 'Weather Forecast', 'Weavo Liquid Loom', 'Webex', 'Webex Integration',
  'Webhood URL Scanner', 'Website Carbon', 'WenDocs Linker', 'What3Words', 'WhatIsMyBrowser', 'WhatsApp', 'Windows 365',
  'WithoutWire Inventory Platform', 'Witivio', 'WMATA', 'WooCommerce', 'Woodpecker', 'Word Cloud by Textvis',
  'Word Online (Business)', 'WordPress', 'Workable', 'Workday HCM', 'Workday SOAP', 'Working days', 'WorkMobile', 'WorkPoint',
  'WorkPoint 365', 'WorkSpan', 'Workstem AU', 'Workstem HK', 'World Academia', 'WorldTime', 'Worldwide Bank Holidays',
  'WP Connectr for WordPress', 'WPForms by Reenhanced LLC', 'WQRM Risk Forecast Services', 'Writesonic', 'wttr.in',
  'X', 'Xbridger Document Manager', 'XC-Gate', 'Xero Accounting - Magnetism', 'xkcd', 'Xooa Blockchain Database',
  'Xooa Blockchain Smart Contract', 'XSOAR', 'XSS PDF Solutions Integrations', 'XSS QR Code Solutions',
  'YakChat', 'Yarado', 'Yeeflow', 'Yeelight', 'Yelp', 'You Need A Budget', 'YouTube', 'YouTube Transcript',
  'Zahara', 'Zanran Scaffolder', 'Zapier MCP', 'Zapier NLA', 'Zellis', 'Zendesk', 'Zenkraft', 'Zenler', 'Zenlogin',
  'Zippopotamus', 'ZIPPYDOC', 'Zoho Mail', 'Zoho Calendar', 'Zoho Invoice Basic', 'Zoho Sign', 'Zoho TeamInbox',
  'Zoho ZeptoMail', 'Zoom Meetings', 'zReports', 'Zuva DocAI', 'Zvanu Parvaldnieks',
];
