/**
 * agentHelperStrategy.ts
 *
 * Default CA/DA strategy implementation for HelperAgent.
 * Most methods return null/false/'default' — the agent creation flow is the common path.
 * ZERO React imports — pure TypeScript logic only.
 */

import type { HelperAgentStrategy, HelperMessageToken, AgentDisplayConfig } from '../../../components/HelperAgent';
import { AgentConfig } from '../../../types';

export const agentHelperStrategy: HelperAgentStrategy = {
  /**
   * Non-DW agents do not have a Day-0 welcome message seeded by the strategy.
   * Their welcome messages are generated dynamically by the fuzzy-create flow.
   */
  getWelcomeMessage(_agentConfig: AgentConfig): string | null {
    return null;
  },

  /**
   * Non-DW agents do not stream a fixed instructions template on Day-0.
   * Instructions are generated by the LLM in response to the user's first message.
   */
  getStreamingInstructions(_agentConfig: AgentConfig): string | null {
    return null;
  },

  /**
   * Returns the day0Prefix system directive for CA/DA agents.
   * DW agents return null here (they use the streaming-instructions flow instead).
   * Workflow agents have their own prefix — handled by workflowHelperStrategy.
   *
   * NOTE: This method is NOT used in the current HelperAgent implementation.
   * The day0Prefix for CA/DA agents is still built inline in HelperAgent.tsx
   * because it requires `isFirstUserMessage` + `isDay0Agent` runtime checks
   * that depend on helperMessages state. Extracted here for completeness and
   * future use when the inline check is ready to be fully delegated.
   */
  getSystemPromptAdditions(_agentConfig: AgentConfig): string | null {
    return null;
  },

  /**
   * CA/DA agents do not intercept messages at the strategy level.
   */
  shouldInterceptMessage(_text: string, _agentConfig: AgentConfig): boolean {
    return false;
  },

  /**
   * CA/DA agents always use the default message token.
   */
  getMessageToken(_agentConfig: AgentConfig): HelperMessageToken {
    return 'default';
  },

  /**
   * CA/DA agents do not show a custom agentName or agentIcon in messages.
   * The CopilotMessage component defaults to the Copilot Studio avatar.
   */
  getAgentDisplayConfig(_agentConfig: AgentConfig): AgentDisplayConfig {
    return {
      agentName: undefined,
      systemColorIcon: undefined,
    };
  },
};
